name: medications
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  build_runner: ^2.4.8
  firebase_core: ^2.27.0
  firebase_remote_config: ^4.3.17
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_inappwebview: ^6.0.0
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.10+1
  get_it: ^7.6.7
  shared_preferences: ^2.2.2
  custom_sliding_segmented_control: ^1.8.2
  cupertino_icons: ^1.0.8
  intl: ^0.18.1
  hive_flutter: ^1.1.0
  hive: ^2.2.3
  modal_bottom_sheet: ^3.0.0
  flutter_bloc: ^8.1.5
  bloc: ^8.1.4
  flutter_local_notifications: ^17.1.1
  timezone: ^0.9.3
  share_plus: ^9.0.0
  in_app_review: ^2.0.9
  package_info_plus: ^8.0.0
  cloud_firestore: ^4.17.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/imgs/
flutter_intl:
  enabled: true
